name: 'Kingly performance'
type: 'Site'
description: 'Configures Kingly performance modules.'
recipes:
  - core/recipes/core_recommended_performance

install:
  - fast404
  - http_cache_control
  - imageapi_optimize
  - minifyhtml
  - purge
  - quicklink
  - ultimate_cron
  - warmer
  - webp

config:
  strict: false
  actions:
    system.performance:
      simpleConfigUpdate:
        cache.page.max_age: 900
        css.preprocess: true
        js.preprocess: true
